### ISSUE TITLE
Illegal callback invocation from native module. This callback type only permits a single invocation from native code.

### ISSUE THREAD

**Issue by mitulverma13** [callstack/react-native-socket-mobile#12]
I am trying to build the app on my iOS device but i am always getting the following error.
![simulator screen shot - iphone xr - 2019-03-01 at 12 51 15](https://user-images.githubusercontent.com/2008835/53731227-1b95c380-3ea0-11e9-8209-6e1ec982f148.png)

**Comment by gblache** [comment]
Did you ever figure this out? I'm getting the same error.

**Comment by mitulverma13** [comment]
No, I am still looking into it. React can only permit single invocation but in this app, they are trying to invoke 3 parameters. App ID, App key and Developers ID due to which this error occurs.

**Comment by gblache** [comment]
This was solved by paying for and using the real App ID, App Key, and Developers ID.

**Comment by mitulverma13** [comment]
Great, are you able to connect with Socket Device?

**Comment by mitulverma13** [comment]
I am still facing the issue, can someone please help me out ?
